application: see-all
version: 1
runtime: go
api_version: go1

# Once it works, increase to 30d.
default_expiration: "1m"

handlers:
- url: /static
  static_dir: static
  secure: always

# Using a static root to reduce the cost.
- url: /
  static_files: static/root.html
  upload: static/root.html
  secure: always

# TODO(maruel): Add one as an IR image.
#- url: /favicon.ico
#  static_files: static/favicon.ico
#  upload: static/favicon.ico
#  secure: always
#  expiration: "30d"

- url: /robot.txt
  static_files: static/robot.txt
  upload: static/robot.txt
  secure: always
  expiration: "30d"

# Do not require login on API.
- url: /api/seeall/.*
  script: _go_app
  secure: always

# Enforce login via AppEngine to save on CPU.
- url: /seeall/.*
  script: _go_app
  secure: always
  login: required

# Enforce login via AppEngine to save on CPU.
- url: /restricted/.*
  script: _go_app
  secure: always
  login: admin

# The app will basically be unusable without it.
inbound_services:
- warmup
